name: web_redrop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  retrofit: ^4.0.3
  dio: ^5.4.0
  http: ^1.1.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  url_strategy: ^0.2.0
  universal_html: ^2.2.4
  intl_utils: ^2.8.6
  json_annotation: ^4.8.1
  data_table_2: ^2.5.10
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  timer_count_down: ^2.2.2
  cloud_firestore: ^4.15.6
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.9
  syncfusion_flutter_xlsio: ^24.2.9
  open_file: ^3.3.2
  flutter_date_range_picker:
  path_provider: ^2.1.2
  syncfusion_flutter_charts: ^24.1.45+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dashboard/

  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
